services:
  mysql:
    image: mysql:8.0
    container_name: mysql_order
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: OrderServiceDb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    restart: unless-stopped

volumes:
  mysql_data: